# Generated by Django 6.0.2 on 2026-02-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_tabel_alter_menuitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tabel',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='tabel',
            name='capacity',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tabel',
            name='qr_code_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tabel',
            name='status',
            field=models.CharField(choices=[('empty', 'خالی'), ('reserved', 'رزرو شده'), ('full', 'اشغال')], default='empty', max_length=10),
        ),
        migrations.AlterField(
            model_name='tabel',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
