# Generated by Django 6.0.2 on 2026-02-27 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_tabel_is_active_remove_tabel_unique_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
